version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: paggo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: paggo
      POSTGRES_PASSWORD: paggo
      POSTGRES_DB: paggo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
